const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const {_electron} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = path.resolve(__dirname,'..');
const output = path.join(root,'.test-output');
fs.mkdirSync(output,{recursive:true});
const profile = fs.mkdtempSync(path.join(output,'profile-'));
const saveFile = path.join(output,'smoke.cutline');
const clipFile = path.resolve(root,'../testmedia/clip1.mp4');
(async()=>{
  const app = await _electron.launch({executablePath:path.join(root,'node_modules/electron/dist/electron.exe'),args:[root],cwd:root,env:{...process.env,CUTLINE_TEST_DIR:profile}});
  try {
    const page = await app.firstWindow();
    console.log('Window URL:',page.url());
    page.on('console',msg=>{if(msg.type()==='error')console.log('Renderer:',msg.text());});
    page.on('dialog',dialog=>{void dialog.dismiss().catch(()=>{});});
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1280,720));
    await page.waitForLoadState('domcontentloaded');
    console.log('Loaded URL:',page.url());
    await page.screenshot({path:path.join(output,'desktop-loaded.png')});
    await page.locator('.import-button').waitFor({timeout:10000});
    await page.screenshot({path:path.join(output,'desktop-empty.png')});
    await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},clipFile);
    await page.locator('.import-button').click();
    await page.locator('.media-card').first().waitFor({timeout:45000});
    await page.locator('.media-card').first().dblclick();
    await page.locator('.clip.selected').waitFor();
    await page.keyboard.press('Control+d');
    assert.equal(await page.locator('.clip').count(),2,'duplicate adds a clip');
    await page.keyboard.press('Control+z');
    assert.equal(await page.locator('.clip').count(),1,'undo reverses duplication');
    await page.keyboard.press('Control+Shift+z');
    assert.equal(await page.locator('.clip').count(),2,'redo restores duplication');
    await page.keyboard.press('Home');
    await page.keyboard.press('Shift+ArrowRight');
    await page.keyboard.press('s');
    assert.equal(await page.locator('.clip').count(),2,'split does not change a different clip when selected clip is outside playhead');
    await page.locator('.clip').first().click();
    await page.keyboard.press('s');
    assert.equal(await page.locator('.clip').count(),3,'selected clip splits at playhead');
    await page.keyboard.press('Control+z');
    assert.equal(await page.locator('.clip').count(),2);
    const videoHead=page.locator('.track-head').filter({hasText:'Video 1'});
    await videoHead.getByTitle('Lock track',{exact:true}).click();
    await page.keyboard.press('Delete');
    assert.equal(await page.locator('.clip').count(),2,'locked track prevents deletion');
    await videoHead.getByTitle('Unlock track',{exact:true}).click();
    await page.getByTitle('Fit timeline').click();
    await page.getByLabel('Project name').fill('Desktop smoke project');
    await page.getByLabel('Project name').press('Tab');
    await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},saveFile);
    await page.keyboard.press('Control+s');
    await page.getByRole('status').filter({hasText:'Project saved.'}).waitFor();
    const saved=JSON.parse(fs.readFileSync(saveFile,'utf8'));
    assert.equal(saved.clips.length,2);assert.equal(saved.name,'Desktop smoke project');
    await page.getByLabel('Dismiss message').click();
    await page.getByRole('button',{name:'Menu'}).click();
    await page.getByRole('button',{name:/New project/}).click();
    assert.equal(await page.locator('.clip').count(),0);
    await app.evaluate(({dialog},file)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:[file]});},saveFile);
    await page.keyboard.press('Control+o');
    await page.locator('.clip').nth(1).waitFor();
    assert.equal(await page.getByLabel('Project name').inputValue(),'Desktop smoke project');
    await page.locator('.clip').first().click();
    await page.waitForFunction(()=>{const v=document.querySelector('.video-layer video');return v&&v.readyState>=2;},{},{timeout:15000});
    console.log('Preview:', await page.locator('.video-layer video').evaluate(v=>({ready:v.readyState,width:v.videoWidth,height:v.videoHeight,error:v.error?.message,current:v.currentTime})));
    await page.screenshot({path:path.join(output,'desktop-first-frame.png')});
    await page.getByTitle('Next frame').click();
    await page.waitForFunction(()=>{const v=document.querySelector('.video-layer video');return v&&!v.seeking&&v.currentTime>0;});
    await page.screenshot({path:path.join(output,'desktop-project.png')});
    const overflow=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,inspector:document.querySelector('.inspector').getBoundingClientRect().right,timeline:document.querySelector('.timeline').getBoundingClientRect().bottom}));
    assert.ok(overflow.inspector<=overflow.width+1,'inspector stays on screen');
    assert.ok(overflow.scroll<=overflow.width,'no horizontal document overflow');
    await page.getByRole('button',{name:'Export',exact:true}).click();
    await page.getByRole('dialog',{name:'Export video'}).waitFor();
    await page.screenshot({path:path.join(output,'desktop-export.png')});
    await page.getByLabel('Resolution',{exact:true}).selectOption('720');
    await page.getByLabel('Quality',{exact:true}).selectOption('draft');
    const exportFile=path.join(output,'desktop-export.mp4');
    await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},exportFile);
    await page.getByRole('dialog').getByRole('button',{name:'Export',exact:true}).click();
    await page.getByText('Exported to '+exportFile,{exact:true}).waitFor({timeout:60000});
    assert.ok(fs.statSync(exportFile).size>1000,'desktop exports a real MP4');
    for(const dims of [[1100,640],[960,600]]) {
      await app.evaluate(({BrowserWindow},dims)=>BrowserWindow.getAllWindows()[0].setSize(...dims),dims);
      await page.waitForFunction(([w,h])=>innerWidth===w&&innerHeight===h,dims);
      const box=await page.locator('.inspector').boundingBox();assert.ok(box.x+box.width<=dims[0]+1);
      await page.screenshot({path:path.join(output,'desktop-'+dims.join('x')+'.png')});
    }
    assert.deepEqual(errors,[],'renderer has no uncaught errors');
    console.log(JSON.stringify({ok:true,checks:['import','duplicate','undo','redo','selected split','track lock','save','new','open','preview frame','1280/1100/960 layout','real desktop MP4 export'],screenshots:output},null,2));
  } finally { await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().forEach(w=>w.destroy())).catch(()=>{}); await app.close().catch(()=>{}); }
  const reopened = await _electron.launch({executablePath:path.join(root,'node_modules/electron/dist/electron.exe'),args:[root],cwd:root,env:{...process.env,CUTLINE_TEST_DIR:profile}});
  try {
    const page=await reopened.firstWindow();
    await page.locator('.clip').nth(1).waitFor();
    assert.equal(await page.getByLabel('Project name').inputValue(),'Desktop smoke project');
    console.log('Draft restoration after restart: passed');
  } finally {await reopened.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows().forEach(w=>w.destroy())).catch(()=>{});await reopened.close().catch(()=>{});}
})().catch(e=>{console.error(e);process.exitCode=1;});

